const sectionLinks = [...document.querySelectorAll('[data-section-link]')];
const sections = [...document.querySelectorAll('[data-section]')];
const mobileNav = document.querySelector('.mobile-nav');
const mobileMoreButton = document.querySelector('.mobile-nav__more');
const mobileMoreMenu = document.querySelector('#mobile-more-menu');
const mobileMoreLinks = [...document.querySelectorAll('.mobile-nav__more-menu [data-section-link]')];
const mobileMoreSectionIds = new Set(mobileMoreLinks.map((link) => link.dataset.sectionLink));
const year = document.querySelector('[data-year]');
const mobileDisclosures = [...document.querySelectorAll('[data-mobile-disclosure]')];
const listeningEndpoint = document.querySelector('meta[name="listening-endpoint"]')?.content;
const listeningPanel = document.querySelector('[data-listening]');
const listeningElements = {
  kicker: document.querySelector('[data-listening-kicker]'), title: document.querySelector('[data-listening-title]'), status: document.querySelector('[data-listening-status]'), current: document.querySelector('[data-listening-current]'), currentArt: document.querySelector('[data-listening-current-art]'), currentFallback: document.querySelector('[data-listening-current-fallback]'), currentLabel: document.querySelector('[data-listening-current-label]'), currentTitle: document.querySelector('[data-listening-current-title]'), currentMeta: document.querySelector('[data-listening-current-meta]'), progressWrap: document.querySelector('[data-listening-progress-wrap]'), progress: document.querySelector('[data-listening-progress]'), history: document.querySelector('[data-listening-history]'), historyTitle: document.querySelector('[data-listening-history-title]'), historySummary: document.querySelector('[data-listening-history-summary]'), list: document.querySelector('[data-listening-list]'), window: document.querySelector('[data-listening-window]'), note: document.querySelector('[data-listening-note]'), refresh: document.querySelector('[data-listening-refresh]'),
};
const reducedMotionQuery = window.matchMedia?.('(prefers-reduced-motion: reduce)');
if (mobileDisclosures.length && window.matchMedia) {
  const query = window.matchMedia('(max-width: 35rem)');
  const sync = ({matches}) => mobileDisclosures.forEach((item) => { item.open = !matches; });
  sync(query); query.addEventListener?.('change', sync);
}
const localTimeElement = document.querySelector('[data-local-time]');
const localDateElement = document.querySelector('[data-local-date]');
const GHANA_TIME_ZONE = 'Africa/Accra';
if (localTimeElement) {
  const timeFormatter = new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:GHANA_TIME_ZONE});
  const dateFormatter = new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:GHANA_TIME_ZONE});
  const render = () => { const now=new Date(); localTimeElement.textContent=timeFormatter.format(now); localTimeElement.dateTime=now.toISOString(); if(localDateElement)localDateElement.textContent=dateFormatter.format(now); };
  render(); window.setInterval(render,1000);
}
let listeningTimer, listeningStarted=false, listeningLoading=false, listeningFailures=0, listeningHasTracks=false, listeningProgressAnimation;
const listeningSnapshot={current:null,recent:null,historyUpdatedAt:0,historyRetryAt:0};
const LISTENING_HISTORY_INTERVAL=120000;
let activeSectionId='about';
const EMAIL_ADDRESS='mpapakojo@gmail.com';
const sideNavElement=document.querySelector('.section-nav');
const mobilePrimaryElement=document.querySelector('.mobile-nav__primary');
function createGlide(container){if(!container)return null;const glide=document.createElement('span');glide.className='nav-glide';glide.setAttribute('aria-hidden','true');container.prepend(glide);return glide;}
const sideGlide=createGlide(sideNavElement),mobileGlide=createGlide(mobilePrimaryElement);
function placeGlides(animated){const apply=()=>{if(sideGlide&&sideNavElement){const a=sideNavElement.querySelector('a.is-active');if(a){const n=sideNavElement.getBoundingClientRect(),r=a.getBoundingClientRect();sideGlide.style.height=r.height+'px';sideGlide.style.transform='translateY('+(r.top-n.top).toFixed(1)+'px)';}}if(mobileGlide&&mobilePrimaryElement){const a=mobilePrimaryElement.querySelector('.is-active');if(a){const n=mobilePrimaryElement.getBoundingClientRect(),r=a.getBoundingClientRect();mobileGlide.style.width=r.width+'px';mobileGlide.style.transform='translateX('+(r.left-n.left).toFixed(1)+'px)';}}};if(!animated){sideGlide?.classList.remove('is-ready');mobileGlide?.classList.remove('is-ready');}apply();requestAnimationFrame(()=>{sideGlide?.classList.add('is-ready');mobileGlide?.classList.add('is-ready');});}
placeGlides(false);window.addEventListener('resize',()=>placeGlides(false),{passive:true});document.fonts?.ready?.then(()=>placeGlides(false));
function mobileMoreMenuOpen(){return Boolean(mobileMoreMenu&&!mobileMoreMenu.hidden);}
function setMoreMenu(open,focusFirst=false,returnFocus=false){if(!mobileMoreButton||!mobileMoreMenu)return;mobileMoreMenu.hidden=!open;mobileMoreButton.setAttribute('aria-expanded',String(open));mobileMoreButton.querySelector('.mobile-nav__more-icon').textContent=open?'×':'+';mobileMoreButton.classList.toggle('is-open',open);mobileMoreButton.classList.toggle('is-active',open||mobileMoreSectionIds.has(activeSectionId));if(open&&focusFirst)requestAnimationFrame(()=>mobileMoreLinks[0]?.focus());if(!open&&returnFocus)mobileMoreButton.focus();}
function setActiveSection(id){activeSectionId=id;sectionLinks.forEach(link=>{const active=link.dataset.sectionLink===id;link.classList.toggle('is-active',active);active?link.setAttribute('aria-current','location'):link.removeAttribute('aria-current');});mobileMoreButton?.classList.toggle('is-active',mobileMoreMenuOpen()||mobileMoreSectionIds.has(id));placeGlides(true);}
function isAtPageBottom(){return window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-24;}
function contactHasEnteredView(){const c=document.querySelector('#contact');if(!c)return false;const b=c.getBoundingClientRect();return b.top<=window.innerHeight*.72&&b.bottom>0;}
setActiveSection('about');
if('IntersectionObserver'in window){const navObserver=new IntersectionObserver(entries=>{if(isAtPageBottom()||contactHasEnteredView()){setActiveSection('contact');return;}const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActiveSection(visible.target.id);},{rootMargin:'-18% 0px -62% 0px',threshold:[0,.12,.35]});sections.forEach(s=>navObserver.observe(s));const reveal=new IntersectionObserver((entries,o)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-revealed');o.unobserve(e.target);}}),{rootMargin:'0px 0px -8% 0px',threshold:.06});sections.forEach(s=>{if(s.getBoundingClientRect().top>window.innerHeight*.92)reveal.observe(s);});}
window.addEventListener('scroll',()=>{if(isAtPageBottom()||contactHasEnteredView())setActiveSection('contact');},{passive:true});
sectionLinks.forEach(link=>link.addEventListener('click',()=>{const id=link.dataset.sectionLink,target=document.getElementById(id);setActiveSection(id);if(mobileMoreSectionIds.has(id))setMoreMenu(false);target?.scrollIntoView({behavior:reducedMotionQuery?.matches?'auto':'smooth',block:'start'});}));
mobileMoreButton?.addEventListener('click',()=>setMoreMenu(!mobileMoreMenuOpen(),!mobileMoreMenuOpen()));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mobileMoreMenuOpen())setMoreMenu(false,false,true);});
document.addEventListener('click',e=>{if(mobileMoreMenuOpen()&&!mobileNav?.contains(e.target))setMoreMenu(false);});
if(year)year.textContent=new Date().getFullYear();
const copyButton=document.querySelector('[data-copy-email]');
copyButton?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(EMAIL_ADDRESS);const label=copyButton.querySelector('[data-copy-label]'),status=copyButton.querySelector('[data-copy-status]');if(label)label.textContent='Copied';if(status)status.textContent='Email address copied';window.setTimeout(()=>{if(label)label.textContent='Copy email';if(status)status.textContent='';},1800);}catch{window.location.href='mailto:'+EMAIL_ADDRESS;}});
function escapeText(value){return String(value??'');}
function setListeningLink(element,url){if(!element)return;if(url){element.href=url;element.target='_blank';element.rel='noopener';element.removeAttribute('aria-disabled');}else{element.removeAttribute('href');element.removeAttribute('target');element.setAttribute('aria-disabled','true');}}
function renderListeningCurrent(state){const e=listeningElements;if(!e.current)return;const track=state?.track;if(!track){e.currentLabel.textContent='Spotify';e.currentTitle.textContent=state?.status==='not_connected'?'Listening connection is offline':'Nothing playing right now';e.currentMeta.textContent='Recent listening is available below when connected.';setListeningLink(e.current,null);if(e.currentArt)e.currentArt.hidden=true;if(e.currentFallback)e.currentFallback.hidden=false;return;}e.currentLabel.textContent=state.status==='playing'?'Playing now':'Played recently';e.currentTitle.textContent=escapeText(track.name);e.currentMeta.textContent=escapeText(track.artist||track.artists||'');setListeningLink(e.current,track.url);if(e.currentArt&&track.image){e.currentArt.src=track.image;e.currentArt.alt='';e.currentArt.hidden=false;if(e.currentFallback)e.currentFallback.hidden=true;}else{if(e.currentArt)e.currentArt.hidden=true;if(e.currentFallback)e.currentFallback.hidden=false;}}
function renderListeningRecent(state){const tracks=state?.tracks||state?.recent||[];if(!listeningElements.list||!Array.isArray(tracks)||!tracks.length)return;listeningElements.list.innerHTML='';tracks.slice(0,5).forEach((track,index)=>{const li=document.createElement('li');li.className='listening-ranking__item';const row=document.createElement(track.url?'a':'div');row.className='listening-row';if(track.url){row.href=track.url;row.target='_blank';row.rel='noopener';}const rank=document.createElement('span');rank.className='listening-rank';rank.textContent=String(index+1).padStart(2,'0');const art=document.createElement('span');art.className='listening-art';if(track.image){const img=document.createElement('img');img.src=track.image;img.alt='';img.loading='lazy';art.append(img);}else art.textContent='♪';const copy=document.createElement('span');copy.className='listening-row__copy';const strong=document.createElement('strong');strong.textContent=escapeText(track.name);const small=document.createElement('small');small.textContent=escapeText(track.artist||track.artists||'');copy.append(strong,small);row.append(rank,art,copy);li.append(row);listeningElements.list.append(li);});}
function renderListeningSnapshot(){if(!listeningPanel)return;listeningPanel.dataset.state=listeningSnapshot.current?.status||'ready';renderListeningCurrent(listeningSnapshot.current);renderListeningRecent(listeningSnapshot.recent);if(listeningElements.status)listeningElements.status.textContent=listeningSnapshot.current?.status==='playing'?'live':'recent';}
async function fetchListeningView(view,signal){const response=await fetch(listeningEndpoint+'?view='+view,{signal,headers:{accept:'application/json'}});const state=await response.json().catch(()=>({status:'unavailable'}));return{response,state};}
function scheduleListeningUpdate(delay){clearTimeout(listeningTimer);if(!document.hidden)listeningTimer=setTimeout(()=>loadListeningState(),delay);}
async function loadListeningState(forceHistory=false){if(!listeningEndpoint||!listeningPanel||listeningLoading)return;listeningStarted=true;listeningLoading=true;const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const refreshRecent=forceHistory||!listeningSnapshot.recent||Date.now()-listeningSnapshot.historyUpdatedAt>=LISTENING_HISTORY_INTERVAL;const requests=[fetchListeningView('current',controller.signal)];if(refreshRecent)requests.push(fetchListeningView('recent',controller.signal));const [current,recent]=await Promise.allSettled(requests);if(current.status==='fulfilled')listeningSnapshot.current=current.value.state;if(refreshRecent&&recent?.status==='fulfilled'){listeningSnapshot.recent=recent.value.state;listeningSnapshot.historyUpdatedAt=Date.now();}listeningFailures=0;renderListeningSnapshot();}catch{listeningFailures+=1;if(listeningElements.status)listeningElements.status.textContent='offline';}finally{clearTimeout(timeout);listeningLoading=false;scheduleListeningUpdate(Math.min(300000,15000*Math.max(1,listeningFailures+1)));}}
if(listeningPanel&&listeningEndpoint){if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){observer.disconnect();loadListeningState();}},{rootMargin:'300px'});observer.observe(listeningPanel);}else loadListeningState();listeningElements.refresh?.addEventListener('click',()=>loadListeningState(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(listeningTimer);else if(listeningStarted)loadListeningState();});}
