// ACCORDION_EVIDENCE_DIR=/tmp/pkm-accordion node cv/tests/accordion-flow.e2e.cjs
const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');const {execFileSync}=require('child_process');const crypto=require('crypto');
const root=path.resolve(__dirname,'..'),out=process.env.ACCORDION_EVIDENCE_DIR||'/tmp/pkm-accordion';fs.mkdirSync(out,{recursive:true});const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const report={timestamp:new Date().toISOString(),revision:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),patchSha256:hash(execFileSync('git',['diff'],{cwd:root})),sourceSha256:hash(['projects/index.html','projects/styles.css','projects/story.js'].map(f=>fs.readFileSync(root+'/'+f)).join('')),harnessSha256:hash(fs.readFileSync(__filename)),node:process.version,boundaries:'Real static HTTP site/Chromium and native disclosure, keyboard, links, image loading. External/API requests fulfilled; WebMCP AbortSignal fixture. Image failure and JS-disabled contexts explicit. No Spotify calls, real analytics writes or mailto activation. No formal assistive-technology/field performance verification.',scenarios:[]};
const server=http.createServer((req,res)=>{try{let relative=new URL(req.url,'http://local').pathname;if(relative.endsWith('/'))relative+='index.html';const file=path.resolve(root,'.'+relative);if(!file.startsWith(root+'/'))throw Error('Path');res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('Not found');}});
let browser,origin,listeningRequests=0;const contexts=[],errors=[];async function check(name,fn){try{await fn();report.scenarios.push({name,result:'pass'});console.log('PASS '+name);}catch(e){report.scenarios.push({name,result:'fail',error:e.stack});console.log('FAIL '+name+' '+e.message);}}
async function pageFor(options={}){const c=await browser.newContext({viewport:{width:1440,height:1000},...options});contexts.push(c);await c.route('**/*',r=>{const u=r.request().url();if(u.includes('/api/listening'))listeningRequests++;if(u.includes('/api/')||!u.startsWith(origin))return r.fulfill({status:204,body:''});return r.continue();});await c.addInitScript(()=>{window.__tools=[];Object.defineProperty(navigator,'modelContext',{value:{registerTool(t,o={}){window.__tools.push(t.name);o.signal?.addEventListener('abort',()=>window.__tools=window.__tools.filter(n=>n!==t.name));}}});});const p=await c.newPage();p.setDefaultTimeout(6000);p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/projects/');return p;}
async function selected(p,key,index){await p.waitForFunction(({key,index})=>document.querySelector('[data-project="'+key+'"]').dataset.activeStage===String(index),{key,index});}
async function noOverflow(p){const overflowing=await p.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>e.tagName+":"+e.className+":"+e.textContent.slice(0,45)));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,JSON.stringify(overflowing));}
(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});report.chromium=browser.version();const p=await pageFor(),keys=['routelab','hayalows','english-chat'];const story=key=>p.locator('[data-project="'+key+'"]');
 await check('All nine original project explanations, evidence caveats and live links retained',async()=>{
  const baseline=execFileSync('git',['show','49f1dff:cv/projects/index.html'],{cwd:root,encoding:'utf8'});const expected=[...baseline.matchAll(/<section><h3>.*?<\/h3><p>(.*?)<\/p><\/section>/g)].map(m=>m[1]);assert.equal(expected.length,9);assert.deepEqual(await p.locator('.story-copy p').allTextContents(),expected);assert.equal(await p.locator('.case__note').count(),3);assert.deepEqual(await p.locator('.case__visit').evaluateAll(es=>es.map(e=>e.href)),['https://maps.hayalows.com/','https://hayalows.com/','https://englishchatsession.vercel.app/']);assert.equal(await p.locator('[data-project-story]').count(),3);
 });
 await check('Each project starts on Problem; native selection is exclusive within its own story',async()=>{
  for(const key of keys){assert.equal(await story(key).locator('details[open]').count(),1);await story(key).getByText('Approach',{exact:true}).click();await selected(p,key,1);assert.equal(await story(key).locator('details[open]').count(),1);assert.equal(await story(key).locator('[data-story-counter]').innerText(),'02 / 03');await story(key).getByText('Evidence',{exact:true}).click();await selected(p,key,2);assert.equal(await story(key).locator('details[open]').count(),1);assert.ok((await story(key).locator('[data-story-context]').innerText()).length>10);assert.equal(await story(key).locator('[data-story-next]').isDisabled(),true);}assert.equal(await p.locator('.story-part[open]').count(),3);await p.locator('#routelab').scrollIntoViewIfNeeded();await p.locator('#routelab').screenshot({path:out+'/desktop-evidence.png'});
 });
 await check('Closing all shows overview; bounded previous/next controls restore correct part',async()=>{
  const s=story('routelab');await s.getByText('Evidence',{exact:true}).click();await selected(p,'routelab','overview');assert.equal(await s.locator('[data-story-counter]').innerText(),'Overview');assert.equal(await s.locator('[data-story-prev]').isDisabled(),true);await s.locator('[data-story-next]').click();await selected(p,'routelab',0);await s.locator('[data-story-next]').click();await selected(p,'routelab',1);await s.locator('[data-story-prev]').click();await selected(p,'routelab',0);assert.equal(await s.locator('[data-story-prev]').isDisabled(),true);
 });
 await check('Scoped arrow/Home/End focus, native Space activation and Escape close/focus',async()=>{
  await p.reload();await selected(p,'routelab',0);const summaries=story('routelab').locator('summary');await summaries.nth(0).focus();await p.keyboard.press('ArrowDown');assert.equal(await summaries.nth(1).evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Space');await selected(p,'routelab',1);await p.keyboard.press('End');assert.equal(await summaries.nth(2).evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');await selected(p,'routelab',2);await p.keyboard.press('Home');await p.keyboard.press('Escape');await selected(p,'routelab','overview');assert.equal(await summaries.nth(2).evaluate(e=>e===document.activeElement),true);
 });
 await check('Authentic previews and full screenshot links; reload resets ephemeral selection',async()=>{
  for(const key of keys){await story(key).locator('img').evaluate(img=>img.decode());assert.ok(await story(key).locator('img').evaluate(img=>img.naturalWidth>0));assert.match(await story(key).getByRole('link',{name:/View full screenshot/}).getAttribute('href'),new RegExp(key+'\\.webp$'));}await p.reload();await selected(p,'routelab',0);assert.equal(await story('routelab').locator('[data-story-counter]').innerText(),'01 / 03');
 });
 await check('320, 375, 768 and 1440 widths preserve all story controls without overflow',async()=>{
  for(const width of [320,375,768,1440]){await p.setViewportSize({width,height:1000});for(const key of keys){await story(key).getByText('Approach',{exact:true}).click();await selected(p,key,1);await noOverflow(p);const controls=await story(key).locator('summary').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().toJSON()));for(const control of controls){assert.ok(control.height>=48);assert.ok(control.x>=0&&control.right<=width+1);}await story(key).getByText('Evidence',{exact:true}).click();await selected(p,key,2);}if(width===375)await p.locator('#routelab').screenshot({path:out+'/phone-evidence.png'});}
 });
 await check('Reduced motion and 200 percent text reflow with no clipped controls',async()=>{
  const z=await pageFor({viewport:{width:375,height:1000},reducedMotion:'reduce'});await z.addStyleTag({content:'html{font-size:200%}'});await z.locator('#routelab summary').nth(1).click();await selected(z,'routelab',1);await noOverflow(z);assert.equal(await z.locator('#routelab .story-context').evaluate(e=>getComputedStyle(e).animationName),'none');for(const button of await z.locator('.story-pagination button').all()){const box=await button.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=376);}await z.locator('#routelab').screenshot({path:out+'/large-text.png'});
 });
 await check('Image failure keeps narrative and live destinations with an honest fallback',async()=>{
  const c=await browser.newContext({viewport:{width:375,height:1000}});contexts.push(c);await c.route('**/assets/projects/*.webp',r=>r.fulfill({status:404,body:''}));await c.route('**/api/**',r=>r.fulfill({status:204,body:''}));const f=await c.newPage();await f.goto(origin+'/projects/');await f.locator('#routelab').scrollIntoViewIfNeeded();await f.locator('#routelab [data-story-image-fallback]').waitFor({state:'visible'});assert.equal(await f.locator('#routelab img').isVisible(),false);await f.locator('#routelab summary').nth(1).click();await selected(f,'routelab',1);assert.equal(await f.locator('#routelab .case__visit').isVisible(),true);await f.locator('#routelab').screenshot({path:out+'/image-failure.png'});
 });
 await check('Without JavaScript every explanation is readable and no dead pagination is shown',async()=>{
  const n=await pageFor({viewport:{width:375,height:1000},javaScriptEnabled:false});assert.equal(await n.locator('.story-part[open]').count(),9);assert.equal(await n.locator('.story-copy p:visible').count(),9);assert.equal(await n.locator('.story-pagination:visible').count(),0);assert.equal(await n.locator('.case__visit').count(),3);await noOverflow(n);await n.locator('#routelab').screenshot({path:out+'/no-javascript.png'});
 });
 await check('Homepage project notes route reaches the correct case and all six WebMCP tools register',async()=>{
  await p.goto(origin+'/');await p.locator('.project-card a[href="projects/#routelab"]').click();await p.waitForURL('**/projects/#routelab');await p.locator('#routelab').waitFor({state:'visible'});await p.waitForFunction(()=>window.__tools.length===6);assert.equal(new Set(await p.evaluate(()=>window.__tools)).size,6);
 });
 await check('No listening requests or uncaught browser errors from the project story flows',async()=>{assert.equal(listeningRequests,0);assert.deepEqual(errors,[]);});
 }catch(e){report.scenarios.push({name:'Harness',result:'fail',error:e.stack});console.error(e);}finally{for(const c of contexts)await c.close();await browser?.close();await new Promise(r=>server.close(r));fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));if(report.scenarios.some(s=>s.result==='fail'))process.exitCode=1;console.log('Evidence: '+out);}})();
