// DESIGN_EVIDENCE_DIR=/tmp/pkm-design node cv/tests/design-gallery-flow.e2e.cjs
const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),out=process.env.DESIGN_EVIDENCE_DIR||'/tmp/pkm-design';fs.mkdirSync(out,{recursive:true});
const catalog=JSON.parse(fs.readFileSync(root+'/design/catalog.json','utf8'));
const report={timestamp:new Date().toISOString(),sourceSha256:crypto.createHash('sha256').update(['design/index.html','design/styles.css','design/gallery.js','design/catalog.json'].map(f=>fs.readFileSync(root+'/'+f)).join('')).digest('hex'),boundaries:'Real local static page and Chromium. External/API requests blocked; no live analytics writes, mail sent or production deployment verification. Image failures/delays explicitly injected. Screen reader semantics inspected; no formal assistive technology or visitor usability study.',scenarios:[]};
const server=http.createServer((req,res)=>{try{let relative=new URL(req.url,'http://local').pathname;if(relative.endsWith('/'))relative+='index.html';const file=path.resolve(root,'.'+relative);if(!file.startsWith(root+'/'))throw Error('Path');res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('Not found');}});
let browser,origin;const contexts=[],errors=[];
async function check(name,fn){try{await fn();report.scenarios.push({name,result:'pass'});console.log('PASS '+name);}catch(e){report.scenarios.push({name,result:'fail',error:e.stack});console.log('FAIL '+name+' '+e.message);}}
async function pageFor(options={}){const c=await browser.newContext({viewport:{width:1440,height:1000},...options});contexts.push(c);await c.route('**/*',r=>r.request().url().startsWith(origin)&&!r.request().url().includes('/api/')?r.continue():r.fulfill({status:204,body:''}));const p=await c.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/design/');return p;}
async function noOverflow(p){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}
async function close(p){await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.viewer').open&&!location.hash.startsWith('#view='));}
async function loaded(p){await p.locator('.viewer-image').waitFor({state:'visible'});assert.ok(await p.locator('.viewer-image').evaluate(e=>e.naturalWidth>0));}
(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});report.chromium=browser.version();const p=await pageFor();
await check('All 67 Drive image files represented with original links and local previews',async()=>{assert.equal(catalog.length,67);assert.equal(new Set(catalog.map(c=>c.id)).size,67);assert.deepEqual(await p.locator('.artwork').evaluateAll(es=>es.map(e=>e.dataset.id)),catalog.map(c=>c.id));for(const c of catalog){assert.ok(fs.existsSync(path.resolve(root+'/design',c.preview)));assert.ok(fs.existsSync(path.resolve(root+'/design',c.full)));assert.match(c.sourceUrl,/drive.google.com\/file\/d\//);assert.ok(c.title&&c.alt&&c.sourceSha256);}assert.equal(await p.locator('.artwork img[alt=""]').count(),0);});
await check('Every imported preview and high-resolution image actually decodes',async()=>{assert.deepEqual(await p.evaluate(async catalog=>{const bad=[];for(const c of catalog)for(const src of [c.preview,c.full]){const img=new Image();img.src=src;try{await img.decode();if(!img.naturalWidth)bad.push(src);}catch{bad.push(src);}}return bad;},catalog),[]);});
await check('Desktop hero and gallery visually captured after real image loading',async()=>{await p.evaluate(async()=>Promise.all([...document.querySelectorAll('.art-deck img')].map(i=>i.decode())));await noOverflow(p);await p.screenshot({path:out+'/desktop.png'});await p.locator('#work').scrollIntoViewIfNeeded();await p.screenshot({path:out+'/desktop-gallery.png'});});
await check('Filter and filename search compose; no-results recovery restores all artwork',async()=>{await p.getByRole('button',{name:'Brand identities',exact:true}).click();assert.equal(await p.locator('.artwork:visible').count(),catalog.filter(c=>c.category==='Brand identities').length);await p.locator('#design-search').fill('Couture');assert.equal(await p.locator('.artwork:visible').count(),1);await p.locator('#design-search').fill('does-not-exist');assert.equal(await p.locator('.no-results').isVisible(),true);await p.getByRole('button',{name:'Show all designs'}).click();assert.equal(await p.locator('.artwork:visible').count(),67);await p.locator('#design-search').fill('IMG_9177');assert.equal(await p.locator('.artwork:visible').count(),1);await p.locator('#design-search').fill('');});
await check('Viewer opens full uncropped artwork with accurate title, filename and source links',async()=>{await p.locator('.artwork__open').first().click();await loaded(p);assert.equal(await p.locator('#viewer-title').innerText(),catalog[0].title);assert.ok((await p.locator('#viewer-category').innerText()).includes(catalog[0].sourceFile));assert.equal(await p.locator('[data-source-link]').getAttribute('href'),catalog[0].sourceUrl);assert.equal(await p.locator('.viewer-image').evaluate(e=>getComputedStyle(e).objectFit),'contain');assert.equal(await p.locator('[data-prev]').isDisabled(),true);assert.equal(await p.locator('[data-close]').evaluate(e=>e===document.activeElement),true);await p.screenshot({path:out+'/desktop-viewer.png'});});
await check('Arrow navigation stays within category results and stops at the boundary',async()=>{await close(p);await p.getByRole('button',{name:'Education',exact:true}).click();const expected=catalog.filter(c=>c.category==='Education');await p.locator('.artwork:visible .artwork__open').first().click();await loaded(p);for(let i=1;i<expected.length;i++){await p.keyboard.press('ArrowRight');await loaded(p);assert.equal(await p.locator('#viewer-title').innerText(),expected[i].title);}assert.equal(await p.locator('[data-next]').isDisabled(),true);await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#viewer-title').innerText(),expected.at(-1).title);await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('#viewer-title').innerText(),expected.at(-2).title);await close(p);await p.getByRole('button',{name:'All work',exact:true}).click();});
await check('Zoom provides a scrollable large image and returns to fit without changing artwork',async()=>{await p.locator('.artwork__open').first().click();await loaded(p);await p.getByRole('button',{name:'Zoom in',exact:true}).click();assert.equal(await p.locator('[data-zoom]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.viewer-stage').evaluate(e=>e.scrollWidth>e.clientWidth),true);await p.getByRole('button',{name:'Fit to screen',exact:true}).click();assert.equal(await p.locator('.viewer-stage').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);await close(p);});
await check('Native modal traps Tab, Escape restores opener and browser Back/Forward works',async()=>{const first=p.locator('.artwork__open').first();await first.focus();await p.keyboard.press('Enter');await loaded(p);for(let i=0;i<10;i++){await p.keyboard.press('Tab');assert.ok(await p.evaluate(()=>document.querySelector('.viewer').contains(document.activeElement)));}await close(p);assert.equal(await first.evaluate(e=>e===document.activeElement),true);await first.click();await loaded(p);await p.goBack();await p.waitForFunction(()=>!document.querySelector('.viewer').open);await p.goForward();await loaded(p);await close(p);});
await check('Direct artwork URL and hero stack both open the correct design',async()=>{await p.goto(origin+'/design/#view='+catalog[1].id);await loaded(p);assert.equal(await p.locator('#viewer-title').innerText(),catalog[1].title);await close(p);await p.locator('[data-deck-id]').last().click();await loaded(p);assert.equal(await p.locator('#viewer-title').innerText(),'Fries Haven is here');await close(p);});
await check('Pointer tilt reacts and motion-off resets it without moving the link hit target',async()=>{const first=p.locator('.artwork__open').first();await first.scrollIntoViewIfNeeded();const box=await first.boundingBox();await p.mouse.move(box.x+box.width*.8,box.y+box.height*.3);await p.waitForFunction(()=>document.querySelector('.artwork [data-tilt]').style.getPropertyValue('--ry')!=='');await p.getByRole('button',{name:'3D motion: on',exact:true}).click();assert.equal(await p.locator('.artwork [data-tilt]').first().evaluate(e=>getComputedStyle(e).transform),'none');await p.getByRole('button',{name:'3D motion: off',exact:true}).click();});
await check('320, 390, 768, 1440 and 1920 layouts preserve controls without horizontal scrolling',async()=>{for(const width of [320,390,768,1440,1920]){await p.setViewportSize({width,height:900});await p.evaluate(()=>scrollTo(0,0));await noOverflow(p);await p.locator('.artwork__open').first().click();await loaded(p);assert.ok(await p.locator('[data-close]').isVisible());assert.ok(await p.locator('[data-source-link]').isVisible());const box=await p.locator('.viewer').boundingBox();assert.ok(box.x>=-1&&box.x+box.width<=width+1);assert.ok(box.y>=-1&&box.y+box.height<=901);await close(p);}});
await check('Mobile touch gallery, full-height viewer and zoom verified and captured',async()=>{const m=await pageFor({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await m.evaluate(async()=>Promise.all([...document.querySelectorAll('.art-deck img')].map(i=>i.decode())));assert.equal(await m.locator('.motion-toggle').isVisible(),false);await noOverflow(m);await m.screenshot({path:out+'/mobile.png'});await m.locator('#work').scrollIntoViewIfNeeded();await m.screenshot({path:out+'/mobile-gallery.png'});await m.locator('.artwork__open').nth(1).tap();await loaded(m);await m.screenshot({path:out+'/mobile-viewer.png'});await m.locator('[data-zoom]').tap();assert.ok(await m.locator('.viewer-stage').evaluate(e=>e.scrollWidth>e.clientWidth));await m.locator('[data-close]').tap();await m.waitForFunction(()=>!document.querySelector('.viewer').open);});
await check('Reduced motion disables depth; 200% text reflows and viewer actions remain reachable',async()=>{const z=await pageFor({viewport:{width:390,height:844},reducedMotion:'reduce'});await z.addStyleTag({content:'html{font-size:200%}'});await noOverflow(z);assert.equal(await z.locator('.motion-toggle').isDisabled(),true);await z.locator('.artwork__open').first().click();await loaded(z);await noOverflow(z);assert.equal(await z.locator('.viewer-image').evaluate(e=>getComputedStyle(e).transform),'none');for(const name of ['[data-close]','[data-zoom]','[data-source-link]']){const box=await z.locator(name).boundingBox();assert.ok(box.x>=0&&box.x+box.width<=391&&box.y>=0&&box.y+box.height<=845,JSON.stringify(box));}await z.screenshot({path:out+'/large-text.png'});});
await check('Image failure offers retry and original link; successful retry restores artwork',async()=>{const f=await pageFor();let blocked=true;await f.context().route('**/assets/design/*-1800.webp',r=>blocked?r.fulfill({status:404,body:''}):r.continue());await f.locator('.artwork__open').first().click();await f.locator('.viewer-error').waitFor({state:'visible'});assert.equal(await f.locator('[data-source-link]').isVisible(),true);assert.equal(await f.locator('[data-zoom]').isDisabled(),true);blocked=false;await f.locator('[data-retry]').click();await loaded(f);});
await check('Slow image loading has honest immediate feedback and preserves the close action',async()=>{const s=await pageFor();let release;const gate=new Promise(r=>release=r);await s.context().route('**/assets/design/*-1800.webp',async r=>{await gate;await r.continue();});await s.locator('.artwork__open').first().click();assert.equal(await s.locator('.viewer-loading').isVisible(),true);assert.equal(await s.locator('[data-close]').isVisible(),true);assert.equal(await s.locator('[data-zoom]').isDisabled(),true);release();await loaded(s);});
await check('No JavaScript keeps all 67 designs and native full-image and portfolio links',async()=>{const n=await pageFor({viewport:{width:390,height:844},javaScriptEnabled:false});assert.equal(await n.locator('.artwork:visible').count(),67);assert.equal(await n.locator('.gallery-tools').isVisible(),false);await noOverflow(n);const href=await n.locator('.artwork__open').first().getAttribute('href');assert.equal(href,catalog[0].full);await n.locator('.artwork__open').first().click();assert.ok(n.url().endsWith(catalog[0].full.slice(2)));});
await check('Homepage graphic design experience and both Explore menus link to gallery',async()=>{await p.goto(origin+'/');assert.equal(await p.locator('.explore__destination[href="design/"]').count(),2);await p.locator('#graphic-design summary').click();assert.equal(await p.locator('#graphic-design a[href="design/"]').isVisible(),true);await p.locator('.design-invitation').click();await p.waitForURL('**/design/');assert.equal(await p.locator('.artwork').count(),67);});
await check('No uncaught errors from graphic design page',async()=>{assert.deepEqual(errors,[]);});
}catch(e){report.scenarios.push({name:'Harness',result:'fail',error:e.stack});console.error(e);}finally{for(const c of contexts)await c.close();await browser?.close();await new Promise(r=>server.close(r));fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));if(report.scenarios.some(s=>s.result==='fail'))process.exitCode=1;console.log('Evidence: '+out);}})();
