// EXPLORE_EVIDENCE_DIR=/tmp/pkm-explore node cv/tests/explore-flow.e2e.cjs
const {chromium}=require('playwright');const fs=require('fs');const http=require('http');const path=require('path');const assert=require('assert/strict');const {execFileSync}=require('child_process');const crypto=require('crypto');
const root=path.resolve(__dirname,'..'),out=process.env.EXPLORE_EVIDENCE_DIR||'/tmp/pkm-explore';fs.mkdirSync(out,{recursive:true});
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const report={timestamp:new Date().toISOString(),revision:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),patchSha256:hash(execFileSync('git',['diff'],{cwd:root})),sourceSha256:hash(['index.html','styles.css','script.js'].map(f=>fs.readFileSync(root+'/'+f)).join('')),harnessSha256:hash(fs.readFileSync(__filename)),node:process.version,boundaries:'Real static HTTP server and Chromium. Listening/analytics and external requests are fulfilled fixtures; WebMCP registration uses AbortSignal fixture. Clipboard success, pending and rejection injected explicitly. No real email sent, API credentials, production CDN or formal assistive-technology verification.',scenarios:[]};
const server=http.createServer((req,res)=>{try{let relative=new URL(req.url,'http://local').pathname;if(relative.endsWith('/'))relative+='index.html';const file=path.resolve(root,'.'+relative);if(!file.startsWith(root+'/'))throw Error('Path');res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('Not found');}});
let browser,origin;const contexts=[];const errors=[];let listeningRequests=0;
async function check(name,fn){try{await fn();report.scenarios.push({name,result:'pass'});console.log('PASS '+name);}catch(e){report.scenarios.push({name,result:'fail',error:e.message});console.log('FAIL '+name+' '+e.message);}}
async function context(options={}){const c=await browser.newContext({viewport:{width:1440,height:1000},...options});contexts.push(c);await c.route('**/*',r=>{const u=r.request().url();if(u.includes('/api/listening')){listeningRequests++;return r.fulfill({json:{status:'not_connected',isPlaying:false,retryAfter:300}});}if(u.includes('/api/')||!u.startsWith(origin))return r.fulfill({status:204,body:''});return r.continue();});await c.addInitScript(()=>{window.__tools=[];Object.defineProperty(navigator,'modelContext',{value:{registerTool(t,o={}){window.__tools.push(t.name);o.signal?.addEventListener('abort',()=>window.__tools=window.__tools.filter(n=>n!==t.name));}}});window.__copyCalls=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText(text){window.__copyCalls.push(text);return new Promise((resolve,reject)=>{window.__copyResolve=resolve;window.__copyReject=()=>reject(new Error('Clipboard denied'));});}}});});return c;}
async function pageFor(options={}){const c=await context(options),p=await c.newPage();p.setDefaultTimeout(6000);p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/');return p;}
async function waitClosed(p,selector){await p.waitForFunction(s=>!document.querySelector(s).open,selector);}
async function settle(p){await p.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));});}
async function noOverflow(p){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}
(async()=>{try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});report.chromium=browser.version();
 const p=await pageFor(),desktop='.explore--desktop',mobile='.explore--mobile';
 await check('Desktop keyboard opening, destination links, Escape and focus return',async()=>{
  const trigger=p.locator(desktop+' > summary');await trigger.focus();await p.keyboard.press('Enter');await p.locator(desktop+' .explore__panel').waitFor({state:'visible'});await p.waitForFunction(()=>document.querySelector('.explore--desktop > summary').getAttribute('aria-expanded')==='true');await p.keyboard.press('Tab');await p.keyboard.press('Tab');assert.equal(await p.locator(':focus').innerText(),'Playground\nPuzzles, maps & a postcard');await settle(p);await p.screenshot({path:out+'/desktop-explore.png'});await p.keyboard.press('Escape');await waitClosed(p,desktop);assert.equal(await trigger.evaluate(e=>e===document.activeElement),true);
 });
 await check('Explore section navigation closes, focuses destination and updates active state',async()=>{
  await p.locator(desktop+' > summary').click();await p.locator(desktop+' a[href="#skills"]').click();await waitClosed(p,desktop);await p.waitForFunction(()=>location.hash==='#skills'&&document.activeElement.id==='skills');assert.equal(await p.locator('.section-nav a[href="#skills"]').getAttribute('aria-current'),'location');
 });
 await check('Real Playground and CV destinations and browser back',async()=>{
  for(const [route,title] of [['playground/','PKM Playground'],['resume/','Papa Kojo']]){await p.locator(desktop+' > summary').click();await p.locator(desktop+' a[href="'+route+'"]').click();await p.waitForURL('**/'+route);assert.match(await p.title(),new RegExp(title));await p.goBack();await p.locator(desktop+' > summary').waitFor({state:'visible'});}
 });
 await check('Outside click, tabbing away, explicit close and repeated toggle',async()=>{
  const trigger=p.locator(desktop+' > summary');await trigger.click();await p.locator('#skills h2').click();await waitClosed(p,desktop);await trigger.click();await p.locator(desktop+' [data-explore-close]').click();await waitClosed(p,desktop);assert.equal(await trigger.evaluate(e=>e===document.activeElement),true);await trigger.click();await trigger.click();await waitClosed(p,desktop);await trigger.focus();await p.keyboard.press('ArrowDown');assert.equal(await p.locator(desktop+' nav a').first().evaluate(e=>e===document.activeElement),true);await p.locator('.hero-actions a').first().focus();await waitClosed(p,desktop);
 });
 const m=await pageFor({viewport:{width:375,height:900},hasTouch:true,isMobile:true});
 await check('Touch Explore at 320, 375 and 768px with readable targets and no overlap',async()=>{
  for(const width of [320,375,768]){await m.setViewportSize({width,height:900});await m.locator(mobile+' > summary').tap();await m.locator(mobile+' .explore__panel').waitFor({state:'visible'});await noOverflow(m);const boxes=await m.locator('.mobile-nav__primary > a,'+mobile+' > summary').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().toJSON()));assert.equal(boxes.length,5);for(let i=0;i<boxes.length;i++){assert.ok(boxes[i].height>=48);if(i)assert.ok(boxes[i-1].right<=boxes[i].left+1);}const panel=await m.locator(mobile+' .explore__panel').boundingBox();assert.ok(panel.x>=0&&panel.x+panel.width<=width+1);assert.ok(panel.y>=0);await settle(m);await m.screenshot({path:out+'/mobile-'+width+'-explore.png'});await m.locator(mobile+' [data-explore-close]').tap();}
 });
 await check('Mobile section selection and direct Contact shortcut',async()=>{
  await m.setViewportSize({width:375,height:900});await m.locator(mobile+' > summary').tap();await m.locator(mobile+' a[href="#education"]').tap();await waitClosed(m,mobile);await m.waitForFunction(()=>document.activeElement.id==='education'&&location.hash==='#education');assert.ok(await m.locator(mobile+' > summary').evaluate(e=>e.classList.contains('is-active')));assert.equal(await m.locator(mobile+' a[href="#education"]').getAttribute('aria-current'),'location');await m.locator('.mobile-nav__primary > a[href="#contact"]').tap();await m.waitForFunction(()=>location.hash==='#contact'&&document.activeElement.id==='contact');await m.waitForFunction(()=>document.querySelector('#contact').getBoundingClientRect().top<innerHeight*.5);await m.screenshot({path:out+'/mobile-contact.png'});
 });
 await check('Resize closes disclosure; short landscape panel stays reachable',async()=>{
  await m.locator(mobile+' > summary').tap();await m.setViewportSize({width:1280,height:900});await waitClosed(m,mobile);await m.setViewportSize({width:768,height:360});await m.locator(mobile+' > summary').tap();await m.locator(mobile+' a[href="#personal"]').scrollIntoViewIfNeeded();const b=await m.locator(mobile+' a[href="#personal"]').boundingBox();assert.ok(b.y>=0&&b.y+b.height<360);await m.screenshot({path:out+'/short-landscape.png'});
 });
 await check('200 percent text and reduced motion reflow',async()=>{
  const z=await pageFor({viewport:{width:375,height:900},reducedMotion:'reduce'});await z.addStyleTag({content:'html{font-size:200%}'});await z.locator(mobile+' > summary').click();await noOverflow(z);assert.equal(await z.locator(mobile+' .explore__panel').evaluate(e=>getComputedStyle(e).animationName),'none');for(const link of await z.locator(mobile+' nav a').all()){await link.scrollIntoViewIfNeeded();const b=await link.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=376);const dock=await z.locator('.mobile-nav').boundingBox();assert.ok(b.y>=0&&b.y+b.height<=dock.y,'Enlarged-text links remain above the dock and reachable');}await z.screenshot({path:out+'/large-text.png'});
 });
 await check('No-JavaScript disclosure, route links and email remain functional',async()=>{
  const n=await pageFor({viewport:{width:375,height:900},javaScriptEnabled:false});await n.locator(mobile+' > summary').click();await n.locator(mobile+' a[href="#skills"]').waitFor({state:'visible'});await n.locator(mobile+' a[href="resume/"]').click();await n.waitForURL('**/resume/');await n.goBack();assert.match(await n.locator('.primary-action').getAttribute('href'),/^mailto:mpapakojo@gmail.com/);assert.equal(await n.locator('[data-copy-email]').isVisible(),false);await noOverflow(n);
 });
 await check('Contact portrait interaction preserves address and accessible link name',async()=>{
  await p.goto(origin+'/#contact');const email=p.getByRole('link',{name:'Email Papa Kojo Mensah at mpapakojo@gmail.com'});await email.focus();await p.waitForFunction(()=>getComputedStyle(document.querySelector('.contact-greeting__personal')).opacity==='1');assert.equal(await email.locator('small').innerText(),'mpapakojo@gmail.com');assert.match(await email.getAttribute('href'),/^mailto:/);await p.waitForFunction(()=>document.querySelector('#contact').getBoundingClientRect().top<innerHeight*.5);await settle(p);await p.screenshot({path:out+'/desktop-contact.png'});
 });
 await check('Unavailable portrait does not remove the email address or contact action',async()=>{
  const c=await context({viewport:{width:375,height:900},reducedMotion:'reduce'});await c.route('**/assets/papa-kojo-portrait.webp',r=>r.fulfill({status:404,body:''}));const broken=await c.newPage();await broken.goto(origin+'/#contact');const email=broken.getByRole('link',{name:'Email Papa Kojo Mensah at mpapakojo@gmail.com'});await email.scrollIntoViewIfNeeded();assert.match(await email.getAttribute('href'),/^mailto:/);assert.equal(await email.locator('small').innerText(),'mpapakojo@gmail.com');assert.equal(await email.isVisible(),true);await noOverflow(broken);
 });
 await check('Clipboard pending blocks duplicate writes; denial is recoverable; retry succeeds',async()=>{
  const copy=p.locator('[data-copy-email]');await copy.click();assert.equal(await copy.isDisabled(),true);assert.equal(await copy.locator('[data-copy-label]').innerText(),'Copying…');await p.evaluate(()=>document.querySelector('[data-copy-email]').click());assert.equal(await p.evaluate(()=>window.__copyCalls.length),1);await p.evaluate(()=>window.__copyReject());await p.locator('[data-copy-feedback]').waitFor({state:'visible'});assert.equal(await copy.locator('[data-copy-label]').innerText(),'Try again');assert.equal(await copy.isDisabled(),false);assert.match(await p.locator('[data-copy-feedback]').innerText(),/Select mpapakojo@gmail.com/);await p.screenshot({path:out+'/copy-failure.png'});await copy.click();await p.evaluate(()=>window.__copyResolve());await p.waitForFunction(()=>document.querySelector('[data-copy-email]').dataset.state==='success');assert.equal(await copy.locator('[data-copy-label]').innerText(),'Copied');assert.equal(await p.locator('[data-copy-feedback]').isVisible(),false);assert.equal(await p.evaluate(()=>window.__copyCalls.length),2);assert.equal(await copy.isDisabled(),false);
 });
 await check('Explore and copy actions add no listening requests; six WebMCP tools remain registered',async()=>{
  const before=listeningRequests;await p.locator(desktop+' > summary').click();await p.keyboard.press('Escape');await p.locator('[data-copy-email]').click();await p.evaluate(()=>window.__copyResolve());assert.equal(listeningRequests,before);await p.waitForFunction(()=>window.__tools.length===6);assert.equal(new Set(await p.evaluate(()=>window.__tools)).size,6);
 });
 await check('No uncaught browser errors',async()=>assert.deepEqual(errors,[]));
 }catch(e){report.scenarios.push({name:'Harness',result:'fail',error:e.stack});console.error(e);}finally{for(const c of contexts)await c.close();if(browser)await browser.close();await new Promise(r=>server.close(r));fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));if(report.scenarios.some(s=>s.result==='fail'))process.exitCode=1;console.log('Evidence: '+out);}})();
