// Run from repo root: FOLDER_EVIDENCE_DIR=/tmp/pkm-project-folders node cv/tests/project-folders-flow.e2e.cjs
const {chromium}=require('playwright');const fs=require('fs');const http=require('http');const path=require('path');const assert=require('assert/strict');const {execFileSync}=require('child_process');const crypto=require('crypto');
const root=path.resolve(__dirname,'..'), out=process.env.FOLDER_EVIDENCE_DIR||'/tmp/pkm-project-folders';
fs.mkdirSync(out,{recursive:true});const report={sourceSha256:crypto.createHash('sha256').update(fs.readFileSync(root+'/project-folders.js')).update(fs.readFileSync(root+'/index.html')).update(fs.readFileSync(root+'/styles.css')).digest('hex'),timestamp:new Date().toISOString(),revision:execFileSync('git',['rev-parse','HEAD'],{cwd:path.dirname(root),encoding:'utf8'}).trim(),patchSha256:crypto.createHash('sha256').update(execFileSync('git',['diff'],{cwd:path.dirname(root)})).digest('hex'),boundaries:'Real static HTTP server and Chromium. API/external requests blocked; native WebMCP registration uses AbortSignal fixture. Image failure and JavaScript-disabled contexts are explicit fixtures. No real provider calls or formal assistive-technology verification.',scenarios:[]};
const server=http.createServer((req,res)=>{try{let relative=new URL(req.url,'http://local').pathname;if(relative.endsWith('/'))relative+='index.html';const file=path.resolve(root,'.'+relative);if(!file.startsWith(root+'/'))throw Error('Path');const ext=path.extname(file);res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.json':'application/json','.svg':'image/svg+xml'})[ext]||'text/plain');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('Not found');}});
let browser,origin;const contexts=[];let apiRequests=0;const errors=[];
async function check(name,fn){try{await fn();report.scenarios.push({name,result:'pass'});console.log('PASS '+name);}catch(error){report.scenarios.push({name,result:'fail',error:error.message});console.log('FAIL '+name+' '+error.message);}}
async function context(options={}){const c=await browser.newContext({viewport:{width:1280,height:1000},...options});contexts.push(c);await c.route('**/*',r=>{const url=r.request().url();if(url.includes('/api/')){apiRequests++;return r.fulfill({status:204,body:''});}return url.startsWith(origin)?r.continue():r.fulfill({status:204,body:''});});await c.addInitScript(()=>{window.__tools=[];Object.defineProperty(navigator,'modelContext',{value:{registerTool(t,options={}){window.__tools.push(t.name);options.signal?.addEventListener('abort',()=>{window.__tools=window.__tools.filter(n=>n!==t.name);});}}});});return c;}
(async()=>{try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});report.chromium=browser.version();
 const c=await context(),p=await c.newPage();p.setDefaultTimeout(6000);p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/#projects');await p.waitForFunction(()=>!document.querySelector('[data-folder-toggle]').hidden);await p.locator('#projects').scrollIntoViewIfNeeded();
 const folder=(key)=>p.locator('[data-project-folder="'+key+'"]');
 await check('Three labelled folders; all existing project links and six WebMCP tools retained',async()=>{assert.equal(await p.locator('[data-folder-toggle]:visible').count(),3);assert.equal(await p.locator('.project-card__actions a').count(),6);await p.waitForFunction(()=>window.__tools.length===6);assert.equal(await p.locator('.design-credit a').getAttribute('href'),'https://rareui.com/');assert.equal(apiRequests,0);});
 await check('Native keyboard activation opens actual image preview; Escape closes and restores focus',async()=>{const button=folder('routelab').locator('[data-folder-toggle]');await button.focus();await p.keyboard.press('Enter');assert.equal(await button.getAttribute('aria-expanded'),'true');assert.equal(await p.locator('#routelab-preview').isVisible(),true);await p.locator('#routelab-preview img').evaluate(i=>i.decode());await p.screenshot({path:out+'/desktop-open.png',fullPage:false});await p.keyboard.press('Escape');assert.equal(await button.getAttribute('aria-expanded'),'false');assert.equal(await button.evaluate(el=>el===document.activeElement),true);await p.keyboard.press('Space');assert.equal(await button.getAttribute('aria-expanded'),'true');});
 await check('Switching/repeated activation and pointer exit are reversible; close restores exact opener',async()=>{const hay=folder('hayalows').locator('[data-folder-toggle]');await hay.click();assert.equal(await p.locator('.project-preview:visible').count(),1);assert.equal(await folder('routelab').locator('[data-folder-toggle]').getAttribute('aria-expanded'),'false');await p.mouse.move(0,0);assert.equal(await hay.getAttribute('aria-expanded'),'true');await hay.click();assert.equal(await p.locator('.project-preview:visible').count(),0);await hay.click();await p.locator('#hayalows-preview [data-folder-close]').click();assert.equal(await hay.evaluate(el=>el===document.activeElement),true);});
 await check('Open/closed previews reflow at phone, tablet and desktop widths without overflow or missing images',async()=>{for(const width of [320,375,560,620,768,1280]){await p.setViewportSize({width,height:900});for(const key of ['routelab','hayalows','english-chat']){const btn=folder(key).locator('[data-folder-toggle]');await btn.click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Overflow at '+width);await p.locator('#'+key+'-preview img').evaluate(i=>i.decode());assert.equal(await p.locator('#'+key+'-preview img').evaluate(i=>i.naturalWidth>0),true);await p.locator('#'+key+'-preview [data-folder-close]').click();}if(width===375){await folder('routelab').scrollIntoViewIfNeeded();await folder('routelab').screenshot({path:out+'/mobile-closed.png'});await folder('routelab').locator('[data-folder-toggle]').click();await folder('routelab').screenshot({path:out+'/mobile-open.png'});await p.keyboard.press('Escape');}}await p.setViewportSize({width:1280,height:1000});await folder('routelab').screenshot({path:out+'/desktop-closed.png'});await p.locator('.project-showcase').screenshot({path:out+'/all-projects.png'});});
 await check('Reload resets ephemeral folder state; public links keep their canonical tracking',async()=>{await folder('english-chat').locator('[data-folder-toggle]').click();await p.reload();assert.equal(await p.locator('.project-preview:visible').count(),0);for(const link of await p.locator('[data-project-link]').all()){assert.equal(new URL(await link.getAttribute('href')).searchParams.get('utm_source'),'pkm_cv');}assert.equal(apiRequests,0);assert.deepEqual(errors,[]);});
 await check('Reduced motion removes folder transitions and 200% text remains usable',async()=>{const c=await context({reducedMotion:'reduce',viewport:{width:620,height:1000}}),page=await c.newPage();await page.goto(origin+'/#projects');await page.locator('[data-folder-toggle]').first().click();assert.equal(await page.locator('.folder-paper').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await page.locator('[data-project-folder]').first().scrollIntoViewIfNeeded();await page.locator('[data-project-folder]').first().screenshot({path:out+'/zoom.png'});const wide=await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1&&getComputedStyle(e).position!=='absolute').slice(0,12).map(e=>({tag:e.tagName,class:e.className,right:e.getBoundingClientRect().right})));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,JSON.stringify(wide));await page.locator('[data-folder-close]').first().click();});
 await check('Blocked images show honest fallback while project links remain available',async()=>{const c=await context();await c.route('**/assets/projects/**',r=>r.abort());const page=await c.newPage();await page.goto(origin+'/#projects');await page.locator('[data-folder-toggle]').first().click();await page.waitForFunction(()=>!document.querySelector('.preview-fallback').hidden);assert.equal(await page.locator('.project-card__actions a:visible').count(),6);});
 await check('Without JavaScript project facts and all six links remain visible; inactive folders hidden',async()=>{const c=await context({javaScriptEnabled:false});const page=await c.newPage();await page.goto(origin+'/#projects');assert.equal(await page.locator('.project-card__actions a:visible').count(),6);assert.equal(await page.locator('[data-folder-toggle]:visible').count(),0);assert.equal(await page.locator('.project-evidence:visible').count(),3);});
 }finally{for(const c of contexts)await c.close().catch(()=>{});if(browser)await browser.close();await new Promise(r=>server.close(r));fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));if(report.scenarios.some(s=>s.result==='fail'))process.exitCode=1;}})();
