(() => {
  const auth=document.querySelector("[data-auth]"),dashboard=document.querySelector("[data-dashboard]"),form=document.querySelector("[data-auth-form]"),keyInput=document.querySelector("#analytics-key"),authStatus=document.querySelector("[data-auth-status]"),status=document.querySelector("[data-status]"),generated=document.querySelector("[data-generated]"),refreshButton=document.querySelector("[data-refresh]"),lockButton=document.querySelector("[data-lock]"),dayButtons=[...document.querySelectorAll("[data-days]")];
  let days=30,key="";
  const fmt=new Intl.NumberFormat("en-GB");
  const countryNames=typeof Intl.DisplayNames==="function"?new Intl.DisplayNames(["en"],{type:"region"}):null;
  const label=value=>String(value??"Unknown");
  const duration=ms=>{const seconds=Math.max(0,Math.round(Number(ms||0)/1000));if(seconds<60)return seconds+"s";const minutes=Math.floor(seconds/60);return minutes+"m "+seconds%60+"s"};
  const countryLabel=code=>{if(!code||code==="Unknown")return"Unknown";try{return countryNames?.of(code)||code}catch{return code}};
  const metric=(name,value)=>{const node=document.querySelector('[data-metric="'+name+'"]');if(node)node.textContent=name==="avg_duration_ms"?duration(value):fmt.format(Number(value||0))};

  function table(name,rows,fields){const body=document.querySelector('[data-table="'+name+'"]');if(!body)return;body.textContent="";if(!rows?.length){const tr=document.createElement("tr"),td=document.createElement("td");td.colSpan=fields.length;td.className="empty-cell";td.textContent="No data yet";tr.append(td);body.append(tr);return}rows.forEach(row=>{const tr=document.createElement("tr");fields.forEach((field,index)=>{const td=document.createElement("td"),raw=row[field.key];td.textContent=index===0?(field.format?field.format(raw):label(raw)):fmt.format(Number(raw||0));tr.append(td)});body.append(tr)})}

  function rankList(name,rows,valueKey="visitors",formatter=label){const root=document.querySelector('[data-list="'+name+'"]');if(!root)return;root.textContent="";if(!rows?.length){root.textContent="No data yet";return}const max=Math.max(...rows.map(row=>Number(row[valueKey]||0)),1);rows.forEach(row=>{const item=document.createElement("div");item.className="rank-row";const copy=document.createElement("div");copy.className="rank-row__copy";const head=document.createElement("div");head.className="rank-row__label";const n=document.createElement("span"),v=document.createElement("span");n.textContent=formatter(row.label);v.textContent=fmt.format(Number(row[valueKey]||0));head.append(n,v);const bar=document.createElement("div");bar.className="rank-row__bar";const fill=document.createElement("i");fill.style.width=Math.max(3,Number(row[valueKey]||0)/max*100)+"%";bar.append(fill);copy.append(head,bar);const strong=document.createElement("strong");strong.textContent=valueKey;item.append(copy,strong);root.append(item)})}

  function chart(rows){const root=document.querySelector("[data-chart]");root.textContent="";if(!rows?.length){const empty=document.createElement("div");empty.className="chart-empty";empty.textContent="Traffic will appear here after the first visits are recorded.";root.append(empty);return}const width=900,height=240,pad={left:36,right:16,top:14,bottom:30},values=rows.map(row=>Number(row.visitors||0)),max=Math.max(...values,1),x=index=>pad.left+(rows.length===1?0:index/(rows.length-1))*(width-pad.left-pad.right),y=value=>height-pad.bottom-(value/max)*(height-pad.top-pad.bottom),points=rows.map((row,index)=>[x(index),y(Number(row.visitors||0))]),line=points.map((point,index)=>(index?"L":"M")+point[0].toFixed(1)+" "+point[1].toFixed(1)).join(" "),area=line+" L "+points[points.length-1][0].toFixed(1)+" "+(height-pad.bottom)+" L "+points[0][0].toFixed(1)+" "+(height-pad.bottom)+" Z",ns="http://www.w3.org/2000/svg",svg=document.createElementNS(ns,"svg");svg.setAttribute("viewBox","0 0 "+width+" "+height);svg.setAttribute("class","traffic-chart");svg.setAttribute("role","img");svg.setAttribute("aria-label","Daily unique visitors");[0,.5,1].forEach(ratio=>{const grid=document.createElementNS(ns,"line"),gy=pad.top+ratio*(height-pad.top-pad.bottom);grid.setAttribute("x1",pad.left);grid.setAttribute("x2",width-pad.right);grid.setAttribute("y1",gy);grid.setAttribute("y2",gy);grid.setAttribute("class","chart-grid");svg.append(grid)});const areaPath=document.createElementNS(ns,"path");areaPath.setAttribute("d",area);areaPath.setAttribute("class","chart-area");svg.append(areaPath);const path=document.createElementNS(ns,"path");path.setAttribute("d",line);path.setAttribute("class","chart-line");svg.append(path);points.forEach((point,index)=>{const circle=document.createElementNS(ns,"circle");circle.setAttribute("cx",point[0]);circle.setAttribute("cy",point[1]);circle.setAttribute("r",rows.length>45?"2":"3");circle.setAttribute("class","chart-point");const title=document.createElementNS(ns,"title");title.textContent=rows[index].day+": "+fmt.format(values[index])+" visitors";circle.append(title);svg.append(circle)});[...new Set([0,Math.floor((rows.length-1)/2),rows.length-1])].forEach(index=>{const text=document.createElementNS(ns,"text");text.setAttribute("x",x(index));text.setAttribute("y",height-8);text.setAttribute("text-anchor",index===0?"start":index===rows.length-1?"end":"middle");text.setAttribute("class","chart-label");text.textContent=new Date(rows[index].day+"T00:00:00Z").toLocaleDateString("en-GB",{day:"numeric",month:"short",timeZone:"UTC"});svg.append(text)});root.append(svg)}

  function recent(rows){const list=document.querySelector("[data-recent]");list.textContent="";if(!rows?.length){const li=document.createElement("li");li.textContent="No recent activity yet.";list.append(li);return}rows.forEach(row=>{const li=document.createElement("li"),time=document.createElement("time"),date=new Date(row.occurred_at);time.dateTime=date.toISOString();time.textContent=date.toLocaleString("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});const main=document.createElement("span");main.className="activity-main";const action=document.createElement("strong");action.textContent=String(row.event_name||"event").replaceAll("_"," ");main.append(action,document.createTextNode(" · "+(row.target||row.section||row.page_path||"/")));const meta=document.createElement("span");meta.className="activity-meta";meta.textContent=(row.country_code?countryLabel(row.country_code):"Unknown")+" · "+(row.device_type||"device")+(row.referrer_host?" · "+row.referrer_host:"");li.append(time,main,meta);list.append(li)})}

  async function load(){if(!key)return;status.classList.remove("is-error");status.textContent="Loading analytics…";refreshButton.disabled=true;try{const response=await fetch("/api/analytics-summary?days="+days,{headers:{"x-analytics-key":key},cache:"no-store"}),data=await response.json().catch(()=>({}));if(response.status===401)throw new Error("That analytics key was not accepted.");if(!response.ok)throw new Error(data.error==="analytics_not_configured"?"The analytics database has not been connected yet.":"Analytics could not be loaded.");["visitors","pageviews","sessions","live_visitors","avg_duration_ms"].forEach(name=>metric(name,data.totals?.[name]));const audience=document.querySelector("[data-audience]");if(audience)audience.textContent=fmt.format(Number(data.audience?.new_visitors||0))+" new · "+fmt.format(Number(data.audience?.returning_visitors||0))+" returning";chart(data.timeline);table("pages",data.pages,[{key:"label"},{key:"visitors"},{key:"pageviews"}]);table("referrers",data.referrers,[{key:"label"},{key:"visitors"},{key:"pageviews"}]);table("actions",data.actions,[{key:"label",format:value=>String(value||"").replaceAll("_"," ")},{key:"visitors"},{key:"events"}]);table("campaigns",data.campaigns,[{key:"label"},{key:"visitors"},{key:"pageviews"}]);rankList("countries",data.countries,"visitors",countryLabel);rankList("devices",data.devices);rankList("browsers",data.browsers);recent(data.recent);generated.textContent="Updated "+new Date(data.generatedAt).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"});status.textContent="Showing the last "+days+" days.";auth.hidden=true;dashboard.hidden=false}catch(error){status.classList.add("is-error");status.textContent=error.message;if(!dashboard.hidden)return;authStatus.textContent=error.message;auth.hidden=false}finally{refreshButton.disabled=false}}

  form.addEventListener("submit",event=>{event.preventDefault();key=keyInput.value.trim();if(!key)return;try{sessionStorage.setItem("pkm_analytics_key",key)}catch{}authStatus.textContent="Checking…";load()});
  dayButtons.forEach(button=>button.addEventListener("click",()=>{days=Number(button.dataset.days||30);dayButtons.forEach(item=>item.classList.toggle("is-active",item===button));load()}));
  refreshButton.addEventListener("click",load);
  lockButton.addEventListener("click",()=>{key="";try{sessionStorage.removeItem("pkm_analytics_key")}catch{}dashboard.hidden=true;auth.hidden=false;keyInput.value="";authStatus.textContent="";keyInput.focus()});
  try{const saved=sessionStorage.getItem("pkm_analytics_key");if(saved){key=saved;keyInput.value=saved;load()}}catch{}
})();
